name: Build and Release Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile row_divider_tool.py
        shell: bash

      - name: Upload Windows Build
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/row_divider_tool.exe

      - name: Upload macOS Build
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/row_divider_tool

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/row_divider_tool.exe
            dist/row_divider_tool
          token: ${{ secrets.GITHUB_TOKEN }}
